// Copyright the Starling authors
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by sdk/tools/gen-fluent-icons.py -- edit the ROLES table there,
// not this file.
//
// Fluent UI System Icons: Microsoft's own icon language, from Microsoft's own
// font, under the MIT licence -- so unlike Segoe Fluent Icons (which the
// Windows shell reads straight out of C:\Windows\Fonts and which cannot be
// redistributed) this one ships with us.
//
// The names are the ROLES the shell draws them in, not the font's catalogue
// names; the mapping to catalogue names is in the generator, and the mapping
// to codepoints is below. Everything is the 24pt cut unless the font has no
// 24 -- the chrome's working size.

import Flutter
import FlutterSwiftBridge
import Foundation

private let _kFontFamily = "FluentSystemIcons"

/// Icons from Microsoft's Fluent UI System Icons font.
///
/// Call `FluentSystemIcons.registerFont()` at startup before using any icon,
/// exactly like `CupertinoIcons`. Both fonts can be registered in the same
/// process; they carry different family names.
public enum FluentSystemIcons {

    /// The font family every icon below is drawn from.
    public static let iconFont = _kFontFamily

    private nonisolated(unsafe) static var _registered = false

    /// Returns the raw font data for loading into the engine.
    ///
    /// **`Bundle.module` is deliberately not used.** SwiftPM's generated
    /// accessor is a `static let` that calls `fatalError` when neither of its
    /// two candidates resolves, so merely REACHING it crashes -- any search
    /// underneath it never runs. Its second candidate is an absolute path into
    /// the build directory that produced the binary, so it resolves on the
    /// machine that built the app and nowhere else. This is a copy of
    /// `CupertinoIcons.fontData()`; keep the two in step.
    public static func fontData() -> Data {
        var roots: [URL] = []
        if let resources = Bundle.main.resourceURL { roots.append(resources) }
        roots.append(Bundle.main.bundleURL)
        roots.append(Bundle.main.bundleURL.appendingPathComponent("Contents/Resources"))
        if let exe = Bundle.main.executableURL?.deletingLastPathComponent() {
            roots.append(exe)
        }
        // `.bundle` is the Darwin name and `.resources` the name SwiftPM uses
        // on Linux and Windows. Searching one suffix silently yields an empty
        // Data() here, which is every icon in the shell drawn as nothing.
        for root in roots {
            for suffix in ["bundle", "resources"] {
                let candidate = root
                    .appendingPathComponent("FlutterSwift_FluentSystemIcons.\(suffix)")
                if let bundle = Bundle(url: candidate),
                   let url = bundle.url(forResource: "FluentSystemIcons-Regular",
                                        withExtension: "ttf"),
                   let data = try? Data(contentsOf: url) {
                    return data
                }
            }
        }
        // Last resort: straight off disk beside the executable, for a layout
        // Bundle() refuses to open at all.
        let execPath = ProcessInfo.processInfo.arguments[0]
        let execDir = (execPath as NSString).deletingLastPathComponent
        var searchPaths: [String] = []
        for dir in [execDir, "\(execDir)/.."] {
            for suffix in ["bundle", "resources"] {
                searchPaths.append(
                    "\(dir)/FlutterSwift_FluentSystemIcons.\(suffix)"
                    + "/FluentSystemIcons-Regular.ttf")
            }
        }
        for path in searchPaths {
            if let data = try? Data(contentsOf: URL(fileURLWithPath: path)) {
                return data
            }
        }
        return Data()
    }

    /// Registers the font with the Flutter engine. Synchronous; safe to call
    /// more than once.
    @discardableResult
    public static func registerFont() -> Bool {
        guard !_registered else { return true }
        let data = fontData()
        guard !data.isEmpty else { return false }
        let success = data.withUnsafeBytes { (buffer: UnsafeRawBufferPointer) -> Bool in
            guard let base = buffer.baseAddress else { return false }
            let ptr = base.assumingMemoryBound(to: UInt8.self)
            return flutter.swift_bridge.LoadFontFromList(ptr, data.count, _kFontFamily)
        }
        if success { _registered = true }
        return success
    }


    // Navigation
    public static let back = IconData(0xf15c, fontFamily: _kFontFamily)
    public static let forward = IconData(0xf182, fontFamily: _kFontFamily)
    public static let up = IconData(0xf19c, fontFamily: _kFontFamily)
    public static let refresh = IconData(0xf13e, fontFamily: _kFontFamily)
    public static let search = IconData(0xf690, fontFamily: _kFontFamily)

    // Caption buttons: the trio every window title bar draws
    public static let chromeMinimize = IconData(0xebd1, fontFamily: _kFontFamily)
    public static let chromeMaximize = IconData(0xe7ec, fontFamily: _kFontFamily)
    public static let chromeRestore = IconData(0xf78c, fontFamily: _kFontFamily)
    public static let chromeClose = IconData(0xf36a, fontFamily: _kFontFamily)

    // Chevrons
    public static let chevronUp = IconData(0xf2b7, fontFamily: _kFontFamily)
    public static let chevronDown = IconData(0xf2a4, fontFamily: _kFontFamily)
    public static let chevronLeft = IconData(0xf2ab, fontFamily: _kFontFamily)
    public static let chevronRight = IconData(0xf2b1, fontFamily: _kFontFamily)

    // The taskbar's status readout
    public static let wifiFull = IconData(0xf8ad, fontFamily: _kFontFamily)
    public static let wifiGood = IconData(0xf8af, fontFamily: _kFontFamily)
    public static let wifiFair = IconData(0xf8b1, fontFamily: _kFontFamily)
    public static let wifiWeak = IconData(0xf8b3, fontFamily: _kFontFamily)
    public static let wifiOff = IconData(0xee5a, fontFamily: _kFontFamily)
    public static let wifiWarning = IconData(0xf7fd, fontFamily: _kFontFamily)
    public static let ethernet = IconData(0xe99a, fontFamily: _kFontFamily)
    public static let network = IconData(0xf45b, fontFamily: _kFontFamily)
    public static let bluetooth = IconData(0xf1df, fontFamily: _kFontFamily)
    public static let airplane = IconData(0xf110, fontFamily: _kFontFamily)
    public static let volume = IconData(0xeb43, fontFamily: _kFontFamily)
    public static let volumeLow = IconData(0xf6fb, fontFamily: _kFontFamily)
    public static let mute = IconData(0xf706, fontFamily: _kFontFamily)
    public static let brightness = IconData(0xe1f8, fontFamily: _kFontFamily)
    public static let battery = IconData(0xe144, fontFamily: _kFontFamily)
    public static let batteryHalf = IconData(0xf1c6, fontFamily: _kFontFamily)
    public static let batteryEmpty = IconData(0xf1bc, fontFamily: _kFontFamily)
    public static let batteryCharging = IconData(0xf1d0, fontFamily: _kFontFamily)
    public static let clock = IconData(0xf2de, fontFamily: _kFontFamily)
    public static let bell = IconData(0xf115, fontFamily: _kFontFamily)
    public static let bellOff = IconData(0xf119, fontFamily: _kFontFamily)
    public static let calendar = IconData(0xe24f, fontFamily: _kFontFamily)
    public static let accessibility = IconData(0xf104, fontFamily: _kFontFamily)
    public static let keyboard = IconData(0xf4b9, fontFamily: _kFontFamily)

    // Start, and the session it can end
    public static let allApps = IconData(0xf138, fontFamily: _kFontFamily)
    public static let apps = IconData(0xf134, fontFamily: _kFontFamily)
    public static let appDefault = IconData(0xf124, fontFamily: _kFontFamily)
    public static let person = IconData(0xf5be, fontFamily: _kFontFamily)
    public static let power = IconData(0xf60f, fontFamily: _kFontFamily)
    public static let restart = IconData(0xf191, fontFamily: _kFontFamily)
    public static let signOut = IconData(0xf6da, fontFamily: _kFontFamily)
    public static let lock = IconData(0xe790, fontFamily: _kFontFamily)
    public static let moon = IconData(0xf87e, fontFamily: _kFontFamily)
    public static let sun = IconData(0xf8a2, fontFamily: _kFontFamily)
    public static let bolt = IconData(0xe619, fontFamily: _kFontFamily)
    public static let settings = IconData(0xf6aa, fontFamily: _kFontFamily)
    public static let personalize = IconData(0xf593, fontFamily: _kFontFamily)
    public static let system = IconData(0xf35a, fontFamily: _kFontFamily)
    public static let pin = IconData(0xf602, fontFamily: _kFontFamily)
    public static let pinOff = IconData(0xf604, fontFamily: _kFontFamily)

    // Menus and command bars
    public static let add = IconData(0xf10a, fontFamily: _kFontFamily)
    public static let cut = IconData(0xf33b, fontFamily: _kFontFamily)
    public static let copy = IconData(0xf32c, fontFamily: _kFontFamily)
    public static let paste = IconData(0xf2d6, fontFamily: _kFontFamily)
    public static let rename = IconData(0xf66a, fontFamily: _kFontFamily)
    public static let share = IconData(0xf6b0, fontFamily: _kFontFamily)
    public static let delete = IconData(0xf34d, fontFamily: _kFontFamily)
    public static let sort = IconData(0xf18b, fontFamily: _kFontFamily)
    public static let more = IconData(0xe825, fontFamily: _kFontFamily)
    public static let openExternal = IconData(0xf583, fontFamily: _kFontFamily)
    public static let info = IconData(0xf4a4, fontFamily: _kFontFamily)
    public static let link = IconData(0xf4e5, fontFamily: _kFontFamily)
    public static let print = IconData(0xf62b, fontFamily: _kFontFamily)
    public static let history = IconData(0xf47f, fontFamily: _kFontFamily)
    public static let favorite = IconData(0xf710, fontFamily: _kFontFamily)
    public static let check = IconData(0xf295, fontFamily: _kFontFamily)
    public static let close = IconData(0xf36a, fontFamily: _kFontFamily)
    public static let edit = IconData(0xf3de, fontFamily: _kFontFamily)
    public static let grid = IconData(0xf463, fontFamily: _kFontFamily)
    public static let window = IconData(0xee5e, fontFamily: _kFontFamily)

    // Places
    public static let folder = IconData(0xf419, fontFamily: _kFontFamily)
    public static let folderOpen = IconData(0xf42f, fontFamily: _kFontFamily)
    public static let zip = IconData(0xf436, fontFamily: _kFontFamily)
    public static let home = IconData(0xf481, fontFamily: _kFontFamily)
    public static let desktop = IconData(0xf35a, fontFamily: _kFontFamily)
    public static let download = IconData(0xf151, fontFamily: _kFontFamily)
    public static let document = IconData(0xf379, fontFamily: _kFontFamily)
    public static let pictures = IconData(0xf489, fontFamily: _kFontFamily)
    public static let music = IconData(0xe855, fontFamily: _kFontFamily)
    public static let video = IconData(0xf84d, fontFamily: _kFontFamily)
    public static let laptop = IconData(0xf4c4, fontFamily: _kFontFamily)
    public static let cloud = IconData(0xf2e5, fontFamily: _kFontFamily)
    public static let drive = IconData(0xf0306, fontFamily: _kFontFamily)
}
