# 500 MB cats, run from INSIDE the terminal under test.
#
#   bigcat500-win.ps1 -Label ours|wt [-Reps 3]
#
# Ghostty's published `time cat` test, at the long round's size. Two files,
# ascii and unicode, generated by gen-bigcat-win.py. Same writer as the suite
# (UTF-8-boundary-safe, see bench-lib.ps1) rather than `cmd /c type`.
param(
    [string]$Label = 'term',
    [int]$Reps = 3,
    # Put the console on UTF-8 before streaming. See Set-Utf8Console.
    [switch]$Utf8,
    [string]$BenchDir = 'C:\bench'
)
$ErrorActionPreference = 'Continue'
. (Join-Path $PSScriptRoot 'bench-lib.ps1')
if ($Utf8) { Set-Utf8Console }

Start-Sleep -Seconds 3
$term = Find-Terminal
$out = "$BenchDir\bigcat500-$Label.txt"
if (-not $term) {
    "no terminal found" | Out-File -Encoding ascii $out
    Start-Sleep 900
    exit 1
}
"# $Label grid=$(Get-Grid) pid=$($term.Pid)" | Out-File -Encoding ascii $out

foreach ($kind in @('ascii', 'unicode')) {
    $f = "$BenchDir\big500-$kind.bin"
    if (-not (Test-Path $f)) {
        Add-Content -Encoding ascii $out "$kind MISSING"
        continue
    }
    for ($r = 1; $r -le $Reps; $r++) {
        Reset-Term
        Start-Sleep -Milliseconds 700
        $c0 = Get-TermCpuMap $term.Pid
        $sw = [System.Diagnostics.Stopwatch]::StartNew()
        Write-Corpus $f
        $sw.Stop()
        $c1 = Get-TermCpuMap $term.Pid
        Reset-Term
        $cpu = Sum-CpuDelta $c0 $c1
        Add-Content -Encoding ascii $out ("{0} {1} {2:N3} {3:N2}" -f $kind, $r, $sw.Elapsed.TotalSeconds, $cpu)
    }
}
Add-Content -Encoding ascii $out ("rss_kb " + (Get-TermRssKb $term.Pid))
Add-Content -Encoding ascii $out ("grid_after " + (Get-Grid))
Start-Sleep 900

